version: "3.8"

services:
  redis:
    image: redis:7
    container_name: anime_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: anime_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: anime_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
