# ==============================
# 📦 docker-compose.yml (루트)
# ==============================

# version: '3.9'

# services:
#   backend:
#     build:
#       context: ./backend
#     container_name: django-backend
#     volumes:
#       - ./backend:/app
#     env_file:
#       - ./backend/.env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend
#     container_name: react-frontend
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "3000:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true

#   db:
#     image: postgres:14
#     container_name: postgres-db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_DB: anime_db
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: adminpw
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data: