# Generated by Django 5.2 on 2025-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boardcomment_is_deleted_boardcomment_tagged_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
