# Generated by Django 5.2 on 2025-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boardpost_likes_alter_postlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
