# Generated by Django 5.2 on 2025-06-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post_create', '게시글 작성'), ('gallery_create', '갤러리 작성'), ('anime_add', '애니 추가'), ('anime_remove', '애니 삭제'), ('review_add', '리뷰 작성'), ('review_remove', '리뷰 삭제'), ('comment_create', '댓글 작성')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_title', models.CharField(blank=True, max_length=255)),
                ('target_image', models.URLField(blank=True)),
                ('parent_author_nickname', models.CharField(blank=True, max_length=255)),
                ('parent_author_profile_image', models.URLField(blank=True, null=True)),
                ('parent_title', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
