# Generated by Django 5.2 on 2025-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_useractivity_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='extra_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
