# Generated by Django 5.2 on 2025-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
