# Generated by Django 5.2 on 2025-06-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_romaji', models.CharField(max_length=255)),
                ('title_native', models.CharField(max_length=255)),
                ('title_ko', models.CharField(max_length=255)),
                ('title_es', models.CharField(max_length=255)),
                ('description_ko', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('format', models.CharField(max_length=50)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('season_ko', models.CharField(blank=True, max_length=50, null=True)),
                ('season_en', models.CharField(blank=True, max_length=50, null=True)),
                ('season_es', models.CharField(blank=True, max_length=50, null=True)),
                ('status_ko', models.CharField(max_length=50)),
                ('status_en', models.CharField(max_length=50)),
                ('status_es', models.CharField(max_length=50)),
                ('source_ko', models.CharField(blank=True, max_length=50, null=True)),
                ('source_en', models.CharField(blank=True, max_length=50, null=True)),
                ('source_es', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image_xl', models.URLField()),
                ('cover_image_l', models.URLField()),
                ('cover_image_m', models.URLField()),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('genres_ko', models.JSONField()),
                ('genres_en', models.JSONField()),
                ('genres_es', models.JSONField()),
                ('studios', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
