# Generated by Django 5.2 on 2025-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_animereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animereview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
