# Generated by Django 5.2 on 2025-06-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_animereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animelist', to='anime.anime'),
        ),
    ]
