# Generated by Django 5.2 on 2025-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_animelist_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='staff',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
