# Generated by Django 5.2 on 2025-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_characters_anime_staff_anime_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='characters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres_es',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres_ko',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='staff',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='anime',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
