# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Build and Push Docker Images
#       run: |
#         docker-compose -f docker-compose.yml build
#         docker-compose -f docker-compose.yml up -d

#     - name: Show Running Containers
#       run: docker ps


name: Log Commits

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  log-commit-info:
    if: ${{ github.event.head_commit && !contains(github.event.head_commit.message, '[bot]') }} # 반복 방지 조건
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Extract commit info
        run: |
          echo "==== New Push ====" >> commit-log.txt
          echo "Time: $(date '+%Y-%m-%d %H:%M:%S')" >> commit-log.txt
          git log -1 --pretty=format:"Author: %an%nMessage: %s%nCommit: %H%n" >> commit-log.txt
          echo "" >> commit-log.txt

      - name: Commit and push log file
        run: |
          git add commit-log.txt
          git commit -m "Update commit-log.txt [bot]" || echo "No changes to commit"
          git push